title: Dataset on Measures of US Expected Inflation before 1978
description: Download the dataset and view figures using it
baseurl: "/web-historicalexpectations" 
url: "https://R2RsquaredLSE.github.io"
github_username: R2RsquaredLSE

theme: jekyll-theme-cayman
